server:
  port: 10086
spring:
  application:
    name: jiyun-eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 100
  server:
    eviction-interval-timer-in-ms: 10000